name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildBackend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
        source-url: https://nuget.pkg.github.com/RafaelJCamara/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_PACKG }}
    - name: Restore dependencies
      run: dotnet restore API/DatingApp.Presentation
    - name: Build
      run: dotnet build API/DatingApp.Presentation --no-restore

  buildFrontend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build frontend
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
    - run: |
        cd client/
        npm ci
    - run: |
        cd client/
        npm run build --if-present